### ISSUE TITLE
mod_tls does not compile with LibreSSL 2.9.x

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [proftpd/proftpd#810]
Proftpd 1.3.6 building against LibreSSL 2.9.2 (and 2.9.1 has same error)

    mod_tls.c: In function 'tls_dotlogin_allow':
    mod_tls.c:7846:5: error: implicit declaration of function 'M_ASN1_BIT_STRING_cmp' [-Werror=implicit-function-declaration]
         if (!M_ASN1_BIT_STRING_cmp(client_sig, file_sig)) {
         ^
    gcc -DHAVE_CONFIG_H  -DLINUX  -I.. -I../include -I/usr/include/mysql -I/usr/include/mysql -I/usr/include/mysql/mysql -I/usr/include -g2 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration -c modules.c
    gcc -DHAVE_CONFIG_H  -DLINUX  -I.. -I../include -I/usr/include/mysql -I/usr/include/mysql -I/usr/include/mysql/mysql -I/usr/include -g2 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration -c mod_ctrls.c
    gcc -DHAVE_CONFIG_H  -DLINUX  -I.. -I../include -I/usr/include/mysql -I/usr/include/mysql -I/usr/include/mysql/mysql -I/usr/include -g2 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration -c mod_lang.c
    cc1: some warnings being treated as errors
    make[1]: *** [mod_tls.o] Error 1

If I apply following patch -

    --- proftpd-1.3.6.orig/contrib/mod_tls.c        2017-04-09 19:31:02.000000000 -0700
    +++ proftpd-1.3.6/contrib/mod_tls.c     2019-05-20 19:50:19.387779159 -0700
    @@ -7839,8 +7839,7 @@
         file_sig = file_cert->signature;
     #endif /* OpenSSL-1.1.x and later */

    -#if OPENSSL_VERSION_NUMBER >= 0x10100000L && \
    -    !defined(HAVE_LIBRESSL)
    +#if OPENSSL_VERSION_NUMBER >= 0x10100000L
         if (!ASN1_STRING_cmp(client_sig, file_sig)) {
     #else
         if (!M_ASN1_BIT_STRING_cmp(client_sig, file_sig)) {

Then the build still fails but in a different place.
I think changes in LibreSSL in 2.9.x API mean build needs adjustment.

The failure with above patch :

    mod_vroot.c: In function 'vroot_pre_pass':
    mod_vroot.c:1473:5: error: 'pr_fs_t' has no member named 'creat'
       fs->creat = vroot_creat;
         ^
    make[1]: *** [mod_vroot.la] Error 1

I *think* that is maybe different issue though?

x86_64 CentOS 7 building in mock buildroot (so I am positive no OpenSSL headers present during build process)

**Comment by AliceWonderMiscreations** [comment]
Just a note - I do plan to look through the mod_tls.c source and try and find everywhere where LibreSSL 2.9.x now supports that part of the OpenSSL 1.1 API - unless someone else already has.

But I'm not a guru is OpenSSL/LibreSSL differences.

**Comment by Castaglia** [comment]
You might try building this using the latest ProFTPD code from the master branch on GitHub; in theory, these libressl/openssl version issues should be addressed in the latest code.

**Comment by AliceWonderMiscreations** [comment]
Just to confirm that the mod_tls.c change I made works when I don't try to build mod_vroot so that is a different issue, well maybe a different issue. Using 1.3.6.

I'll run test suite to make sure, still trying to find a list of OpenSSL 1.1.x API that is now in LibreSSL.

It's *possible* the mod_vroot issue is caused by a Fedora patch applied to it, I think the fedora patch is from 1.3.5 branch so I'll try without the patch.

**Comment by AliceWonderMiscreations** [comment]
Okay when not building `mod_vroot` which is external, build passes and tests pass *outside* of mock build environment when I apply the changes in https://github.com/proftpd/proftpd/commit/389cc579bc8d5704f9dcc2fd01ffd6307aee6b2b to the 1.3.6 source.

Inside of mock I still get a few test errors -

[alice@localhost tests]$ grep -v "Passed" api-tests.log |grep -v "Running"
    api/netaddr.c:154:F:base:netaddr_get_addr_test:0: Failed to get addr for 'www.google.com': No such file or directory
    api/netaddr.c:908:F:base:netaddr_get_dnsstr_list_test:0: Failed to resolve 'www.google.com': No such file or directory
    api/netaddr.c:1088:F:base:netaddr_is_loopback_test:0: Failed to resolve 'www.google.com': No such file or directory
    api/fsio.c:467:F:base:fsio_sys_read_test:0: Failed to read 1 byte: Operation not permitted
    api/inet.c:529:E:base:inet_connect_ipv4_test:0: (after this point) Test timeout expired
    Results for all suites run:
    99%: Checks: 584, Failures: 4, Errors: 1

So with LibreSSL 2.9.2 in 1.3.6 anyway just the small patch in my opening post is needed. Other issues are already fixed in that commit or influenced by mock build environment (e.g. no name resolution causing the google error) and I can probably track those down, but they clearly are not LibreSSL related.

As far as build issue if you want to close feel free, I will look at what changes (if any) need to be made in master for LibreSSL but right now I'm building a package for 3rd party repo and tagged stable is preferable for that.

**Comment by Castaglia** [comment]
I think you also need to be using `mod_vroot` 0.9.4 or later, against a newer ProFTPD, to address the `mod_vroot.c` build issue.

**Comment by Castaglia** [comment]
A fix for this has been committed to the master branch, and backported to the 1.3.6 branch.  Thanks!
