### ISSUE TITLE
mod_tls fails to compile against OpenSSL 3.0.8 due to missing ENGINE_METHOD_ flags

### ISSUE THREAD

**Issue by raffe1234** [proftpd/proftpd#1689]
Hi! I have had some problems compiling proftpd on my qnap with Entware. I have these packages available for me:
http://bin.entware.net/x64-k3.2/
```
opkg update
Downloading http://bin.entware.net/x64-k3.2/Packages.gz
```

I even have proftpd there, but without TLS. I have done a **opkg update && opkg upgrade**

My NAS
```
cat /etc/*release
NAME="QTS"
VERSION="5.0.1 (20230322)"
ID=qts
PRETTY_NAME="QTS 5.0.1 (20230322)"
VERSION_ID="5.0.1"

uname -a
Linux TS-653A 5.10.60-qnap #1 SMP Wed Mar 22 20:14:48 CST 2023 x86_64 GNU/Linux

openssl version -a
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
built on: Fri Jun  2 13:56:39 2023 UTC
platform: linux-x86_64-openwrt
options:  bn(64,64)
compiler: x86_64-openwrt-linux-gnu-gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -pipe -fomit-frame-pointer -fno-caller-saves -fhonour-copts -ffunction-sections -fdata-sections -O3 -DPIC -fpic -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DZLIB -DZLIB_SHARED -DNDEBUG -DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1 -DOPENSSL_PREFER_CHACHA_OVER_GCM
OPENSSLDIR: "/opt/etc/ssl"
ENGINESDIR: "/opt/lib/engines-3"
MODULESDIR: "/opt/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x43d8e3bfefebffff:0x2282
```
I have tried to follow the NAS Entware suggestions of compiling here https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation

It worked with 1.3.6, but not with 1.3.7 or 1.3.8. I do it like this:

```
wget ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.7f.tar.gz
tar -xzf proftpd-1.3.7f.tar.gz
cd proftpd-1.3.7f
./configure --with-modules=mod_tls --prefix=/opt --with-lastlog --enable-dso
```

It ends with this:
```
Build Summary
--------------
Building the following static modules:
  mod_auth_pam
  mod_tls
  mod_cap
```

The whole process is here: https://pastebin.com/AC6RA6Vj

Then I try **make**, it ends with this:
```
...
....
mod_tls.c:18389:15: warning: implicit declaration of function 'ENGINE_set_default'; did you mean 'NCONF_default'? [-Wimplicit-function-declaration]
           if (ENGINE_set_default(e, ENGINE_METHOD_ALL)) {
               ^~~~~~~~~~~~~~~~~~
               NCONF_default
mod_tls.c:18389:37: error: 'ENGINE_METHOD_ALL' undeclared (first use in this function); did you mean 'EC_KEY_METHOD_new'?
           if (ENGINE_set_default(e, ENGINE_METHOD_ALL)) {
                                     ^~~~~~~~~~~~~~~~~
                                     EC_KEY_METHOD_new
mod_tls.c:18389:37: note: each undeclared identifier is reported only once for each function it appears in
mod_tls.c:18390:13: warning: implicit declaration of function 'ENGINE_finish' [-Wimplicit-function-declaration]
             ENGINE_finish(e);
             ^~~~~~~~~~~~~
mod_tls.c:18391:13: warning: implicit declaration of function 'ENGINE_free'; did you mean 'NCONF_free'? [-Wimplicit-function-declaration]
             ENGINE_free(e);
             ^~~~~~~~~~~
             NCONF_free
make[1]: *** [Makefile:31: mod_tls.o] Error 1
make[1]: Leaving directory '/share/CACHEDEV1_DATA/.qpkg/Entware-3x/tmp/proftpd/proftpd-1.3.7f/modules'
make: *** [Makefile:57: modules] Error 2
[/opt/tmp/proftpd/proftpd-1.3.7f] #
```

The whole process is here: https://pastebin.com/30MUKnws

I have tried some random stuff, like:
edit contrib/mod_tls.cand edit manually (naive, right?)
ENGINE_METHOD_ALL > EC_KEY_METHOD_new
SSL_TICKET_RETURN > OCSP_CERTSTATUS
SSL_TICKET_STATUS > OCSP_CERTSTATUS
make clean
./configure --with-modules=mod_tls --prefix=/opt --with-lastlog --enable-dso
./configure --enable-dso --with-shared=mod_tls --prefix=/opt --with-lastlog
./configure --with-modules=mod_tls --prefix=/opt --with-lastlog --enable-dso --with-includes=/opt/include/openssl/ --with-libraries=/opt/lib/
./configure --with-modules=mod_tls --prefix=/opt --with-lastlog --enable-dso --with-includes=/opt/include/
sh ./configure --with-modules=mod_tls --prefix=/opt --with-lastlog --enable-dso --with-includes=/opt/include/

When I today tried with proftpd 1.3.8

```
[/opt/tmp/proftpd] # wget ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.8.tar.gz
--2023-07-09 10:40:20--  ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.8.tar.gz
           => 'proftpd-1.3.8.tar.gz'
Resolving ftp.proftpd.org... 86.59.114.198, 2001:858:2:5::5
Connecting to ftp.proftpd.org|86.59.114.198|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /distrib/source ... done.
==> SIZE proftpd-1.3.8.tar.gz ... 19744412
==> PASV ... done.    ==> RETR proftpd-1.3.8.tar.gz ... done.
Length: 19744412 (19M) (unauthoritative)

proftpd-1.3.8.tar.gz           100%[=================================================>]  18.83M  10.1MB/s    in 1.9s

2023-07-09 10:40:22 (10.1 MB/s) - 'proftpd-1.3.8.tar.gz' saved [19744412]

[/opt/tmp/proftpd] # tar -xzf proftpd-1.3.8.tar.gz
[/opt/tmp/proftpd] # cd proftpd-1.3.8
[/opt/tmp/proftpd/proftpd-1.3.8] #
```
I try
`./configure --with-modules=mod_tls --prefix=/opt --with-lastlog --enable-dso --with-includes=/opt/include/ `
Seems to work as with 1.3.7 above:
https://pastebin.com/Rn5cWazt

But **make** ends with
```
mod_tls.c:11512:12: warning: 'tls_ocsp_cache_open' defined but not used [-Wunused-function]
 static int tls_ocsp_cache_open(char *info) {
            ^~~~~~~~~~~~~~~~~~~
mod_tls.c:734:26: warning: 'tls_ocsp_cache' defined but not used [-Wunused-variable]
 static tls_ocsp_cache_t *tls_ocsp_cache = NULL;
                          ^~~~~~~~~~~~~~
make[1]: *** [Makefile:31: mod_tls.o] Error 1
make[1]: Leaving directory '/share/CACHEDEV1_DATA/.qpkg/Entware-3x/tmp/proftpd/proftpd-1.3.8/modules'
make: *** [Makefile:57: modules] Error 2
```
The whole make process is here https://pastebin.com/81KrrQSs

I do not really understand what the problem is, so it is hard to try to solve it.
/raffe

**Comment by Castaglia** [comment]
First, I recommend that you do a `make clean` before each `./configure` attempt, to remove any of the generated build instructions before doing a completely new build.

Next, as I have no access to any QNAP machine, I will have to guess about what the issues are.   The `warning` messages emitted are just those -- warnings -- and so they are not what is causing the compiler to error out.  That culprit looks to be:
```
mod_tls.c:18893:37: error: 'ENGINE_METHOD_ALL' undeclared (first use in this function); did you mean 'EC_KEY_METHOD_new'?
           if (ENGINE_set_default(e, ENGINE_METHOD_ALL)) {
                                     ^~~~~~~~~~~~~~~~~
```
and that, in turn, is related to use of OpenSSL 3.x (where they are changing _many_ of their APIs, causing problems all across the opensource world).

Now it's possible that the above errors would be different if you do a `make clean` first, before each `configure`.

**Comment by raffe1234** [comment]
Thank you for your answer! Yes, I have done `make clean` (or just deleted the folder) between every attempt. But I suspect you are right about OpenSSL3, that is the main change between when compiling worked and now when compiling do not work. And I have tried a few versions of proftpd:

```
[/opt/tmp] # cd proftpd/
[/opt/tmp/proftpd] # ls
gnu-keyring.gpg        proftpd-1.3.7c/        proftpd-1.3.7f.tar.gz  proftpd-1.3.8rc4.tar.gz
proftpd-1.3.6d/        proftpd-1.3.7c.tar.gz  proftpd-1.3.8/         proftpd-1.3.8.tar.gz
proftpd-1.3.6d.tar.gz  proftpd-1.3.7f/        proftpd-1.3.8rc4/
```
Before I could compile 1.3.6 every time, but now

```
[/opt/tmp/proftpd] # wget ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.6.tar.gz
--2023-07-09 18:10:49--  ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.6.tar.gz
           => 'proftpd-1.3.6.tar.gz'
Resolving ftp.proftpd.org... 86.59.114.198, 2001:858:2:5::5
Connecting to ftp.proftpd.org|86.59.114.198|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /distrib/source ... done.
==> SIZE proftpd-1.3.6.tar.gz ... 20251898
==> PASV ... done.    ==> RETR proftpd-1.3.6.tar.gz ... done.
Length: 20251898 (19M) (unauthoritative)

proftpd-1.3.6.tar.gz        100%[=========================================>]  19.31M  4.95MB/s    in 3.9s

2023-07-09 18:10:54 (4.90 MB/s) - 'proftpd-1.3.6.tar.gz' saved [20251898]

[/opt/tmp/proftpd] # tar -xzf proftpd-1.3.6.tar.gz
[/opt/tmp/proftpd] # cd proftpd-1.3.6
[/opt/tmp/proftpd/proftpd-1.3.6] # sh ./configure --with-modules=mod_tls --prefix=/opt --with-lastlog --enable-dso --with-includes=/opt/include/
```
Seems to work: https://pastebin.com/Y2BPs2ay

But nowdays make ends after OpenSSL3 with (this time I tried with `make -j$(nproc) V=1` that show more info) :

```
/opt/bin/ld: /lib/../lib64/libssl.so: undefined reference to `COMP_CTX_get_method@OPENSSL_1_1_0'
/opt/bin/ld: /lib/../lib64/libssl.so: undefined reference to `BIO_free@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
make: *** [Makefile:62: ftpdctl] Error 1
make: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/share/CACHEDEV1_DATA/.qpkg/Entware-3x/tmp/proftpd/proftpd-1.3.6/modules'
make: *** [Makefile:39: modules] Error 2
```

All: https://pastebin.com/i85A5up2

**Comment by Castaglia** [comment]
I see.  The OpenSSL 3.x series keeps changing these as they go.  Sigh.  I'll see what I can do to detect the absence/presence of these `ENGINE_METHOD_XXX` macros, to handle such build issues going forward.

**Comment by raffe1234** [comment]
I add here also a compile try today of `proftpd-1.3.8` with `make -j$(nproc) V=1` if you need the extra verbose output also with that version.

`./configure --with-modules=mod_tls --prefix=/opt --with-lastlog --enable-dso --with-includes=/opt/include/`
Output here: https://pastebin.com/r886iTux

`make -j$(nproc) V=1`
Output here: https://pastebin.com/uLjhD5Wh

**Comment by Castaglia** [comment]
Thanks.  Interestingly, I just compiled and installed OpenSSL 3.0.8 locally, and compiled ProFTPD 1.3.8, with mod_tls, successfully with that installation.  Given how configurable OpenSSL 3.x is, there's probably some other tweak that's different between my local installation, your OpenSSL 3.x installation, so my local test doesn't reveal as much as I'd hoped.

**Comment by Castaglia** [comment]
This should now be fixed in `master` (and backported to the 1.3.8 branch).
