### ISSUE TITLE
ProFTPD 1.3.5b mod_tls module fails to build with OpenSSL 1.1.1d on Debian 10

### ISSUE THREAD

**Issue by lining5** [proftpd/proftpd#1309]
### What I Did

system: debian10
proftpd version:1.35b
```
./configure --with-modules=mod_tls 
make
```

when I run `make`，It take’s error.

**erro：**
```
gcc -DHAVE_CONFIG_H  -DLINUX  -I.. -I../include  -O2 -Wall -c mod_tls.c
mod_tls.c: In function ‘get_dh512’:
mod_tls.c:114:5: error: dereferencing pointer to incomplete type ‘DH’ {aka ‘struct dh_st’}
   dh->p = BN_bin2bn(dh512_p, sizeof(dh512_p), NULL);
     ^~
mod_tls.c: In function ‘tls_diags_cb’:
mod_tls.c:584:22: error: ‘SSL_ST_OK’ undeclared (first use in this function); did you mean ‘TLS_ST_OK’?
     if (ssl_state == SSL_ST_OK) {
                      ^~~~~~~~~
                      TLS_ST_OK
mod_tls.c:584:22: note: each undeclared identifier is reported only once for each function it appears in
mod_tls.c:594:22: error: ‘SSL3_ST_SR_CLNT_HELLO_A’ undeclared (first use in this function); did you mean ‘TLS_ST_SR_CLNT_HELLO’?
     if (ssl_state == SSL3_ST_SR_CLNT_HELLO_A ||
                      ^~~~~~~~~~~~~~~~~~~~~~~
                      TLS_ST_SR_CLNT_HELLO
mod_tls.c:595:22: error: ‘SSL23_ST_SR_CLNT_HELLO_A’ undeclared (first use in this function); did you mean ‘TLS_ST_SR_CLNT_HELLO’?
         ssl_state == SSL23_ST_SR_CLNT_HELLO_A) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~
                      TLS_ST_SR_CLNT_HELLO
mod_tls.c:632:28: error: ‘SSL_ST_RENEGOTIATE’ undeclared (first use in this function); did you mean ‘SSL_F_SSL_RENEGOTIATE’?
     } else if (ssl_state & SSL_ST_RENEGOTIATE) {
                            ^~~~~~~~~~~~~~~~~~
                            SSL_F_SSL_RENEGOTIATE
mod_tls.c: In function ‘tls_cert_match_dns_san’:
mod_tls.c:1097:9: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
         dns_san = (char *) ASN1_STRING_data(alt_name->d.ia5);
```

### What I Expected/Wanted

How can I install it correctly ？

**Comment by lining5** [comment]
Are there any requirements for the OpenSSL version?

**Comment by Castaglia** [comment]
What does `openssl version -a` show on your system?

**Comment by lining5** [comment]
OpenSSL 1.1.1d  10 Sep 2019
built on: Mon Mar 22 23:08:47 2021 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-AWQHHq/openssl-1.1.1d=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific

**Comment by Castaglia** [comment]
Thanks!  Do you also have the `libssl-dev` package installed?  The above compile errors make it look like the necessary OpenSSL library headers are not being used...

**Comment by lining5** [comment]
I  had installed the libssl-dev.
when I installing the libbl-dev,It's prompt that I have installed


apt-get install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.1.1d-0+deb10u6).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by lining5** [comment]
mod_tls.c: In function ‘tls_setup_cert_dn_environ’:
mod_tls.c:5243:46: error: dereferencing pointer to incomplete type ‘X509_NAME’ {aka ‘struct X509_name_st’}
   for (i = 0; i < sk_X509_NAME_ENTRY_num(name->entries); i++) {
                                              ^~
mod_tls.c:5245:32: error: dereferencing pointer to incomplete type ‘X509_NAME_ENTRY’ {aka ‘struct X509_name_entry_st’}
     int nid = OBJ_obj2nid(entry->object);
                                ^~
mod_tls.c: In function ‘tls_setup_environ’:
mod_tls.c:5488:34: error: dereferencing pointer to incomplete type ‘SSL_SESSION’ {aka ‘struct ssl_session_st’}
       for (i = 0; i < ssl_session->session_id_length; i++) {
                                  ^~
mod_tls.c: In function ‘tls_verify_cb’:
mod_tls.c:5630:21: error: dereferencing pointer to incomplete type ‘X509_STORE_CTX’ {aka ‘struct x509_store_ctx_st’}
     verify_err = ctx->error;
                     ^~
mod_tls.c: In function ‘tls_verify_crl’:
mod_tls.c:5694:15: error: storage size of ‘obj’ isn’t known
   X509_OBJECT obj;
               ^~~
mod_tls.c:5698:18: error: storage size of ‘store_ctx’ isn’t known
   X509_STORE_CTX store_ctx;
                  ^~~~~~~~~
mod_tls.c:5781:30: error: dereferencing pointer to incomplete type ‘X509_CRL’ {aka ‘struct X509_crl_st’}
     ASN1_UTCTIME_print(b, crl->crl->lastUpdate);
                              ^~
mod_tls.c:5809:7: warning: implicit declaration of function ‘X509_OBJECT_free_contents’;

**Comment by lining5** [comment]
When I run in Ubuntu 16.04 64, It's Ok.
OpenSSL 1.0.2g  1 Mar 2016

**Comment by Castaglia** [comment]
Did you run a `make clean` first, before running `./configure --with-modules=mod_tls`?

**Comment by lining5** [comment]
I run in a fressh install。
Debian 10    It‘s error。

Ubuntu 16.04  It’s Ok。

**Comment by Castaglia** [comment]
Interesting.  On Debian 10, the latest ProFTPD source code compiles without issue.  This, to me, indicates that there is something different with the Debian 10 OpenSSL library, such that the _old ProFTPD code_ does not build with it; I'll have to see why.  (I suspect that the newer OpenSSL library on Debian 10, which its changed APIs and structures, can no longer be used by old code which isn't aware of those changes.)

However, the 1.3.5 series of ProFTPD is no longer supported, so there will be no backports/fixes for this.  Any particular reason you are building ProFTPD 1.3.5b from source, rather than using the latest ProFTPD code?

**Comment by lining5** [comment]
We tried the following versions

proftpd1.36   rnto（lowercase） is not working
proftpd1.37  mod_rewrite ()  can not working

<IfModule mod_rewrite.c>
RewriteEngine     on
RewriteMap        tlwr int:tolower
RewriteCondition  %m  USER
RewriteRule       ^(.*)   ${tlwr:$1|}

</IfModule>


In the current production environment, we use proftpd1.35 in debian9,
We want to upgrade debian9 to debian10.
However, we found that the version of proftpd installed on Debian 10 could not meet our requirements
The modules we use are mod_ rewrite，mod_ tls mod_rewrite，mod_tls

**Comment by Castaglia** [comment]
If you are compiling from source, the latest code in the master branch (and in the 1.3.7 branch) from GitHub has mod_rewrite/PCRE fixes (Issue #1300) applied/committed.  That should meet all of your requirements.

**Comment by lining5** [comment]
I tried proftpd1.37, It is OK。
thank you  very much .

**Comment by Castaglia** [comment]
Glad to hear that you now have a working build.  Mind if I close this issue, then?

**Comment by lining5** [comment]
You can close it. Thank you very much ！
