### ISSUE TITLE
mod_digest build error with Alpine 3.7 or 3.8

### ISSUE THREAD

**Issue by tspicer** [proftpd/proftpd#737]
### What I Did

Using Alpine 3.6 and an older commit (4a3610c2650fa630ab90dcb3f854655edf1f3cde) proftpd compiles. Also using Alpine 3.7 and a commit (b08318ee7730270250eb3e6309c81abd8ac9a3b7) seems to work. However, trying to do a build using Alpine 3.7 and 3.8 with more recent commits I get the error below

### What I Expected/Wanted

To be able to build recent commits with Alpine 3.7 or Alpine 3.8

### ProFTPD Version and Configuration

```
&& ./configure '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libexecdir=/usr/libexec/proftpd' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--localstatedir=/var/run/proftpd' '--disable-auth-pam' '--disable-strip' '--enable-dso' '--enable-facl' '--disable-ipv6' '--enable-nls' '--enable-openssl' '--enable-ctrls' '--enable-pcre' '--enable-autoshadow' '--enable-tunable-buffer-size' '--enable-sendfile' '--enable-ipv6' '--enable-dso' '--with-libraries=/usr/lib' '--with-includes=/usr/include/mysql' '--with-includes=/usr/include/libxml2' '--with-modules=mod_aws:mod_readme:mod_dynmasq' '--with-shared=mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_sql:mod_sql_passwd:mod_sql_mysql:mod_ban:mod_facl:mod_rewrite:mod_site_misc:mod_ifversion:mod_dnsbl:mod_qos:mod_sftp:mod_sftp_sql:mod_ifsession:mod_quotatab:mod_quotatab_file:mod_quotatab_sql:mod_exec:mod_digest:mod_geoip:mod_statcache:mod_proxy_protocol' \
    && make \
    && make install
```

The build error:

```
libtool: link: ar cru .libs/mod_exec.a  mod_exec.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/mod_exec.a
libtool: link: ( cd ".libs" && rm -f "mod_exec.la" && ln -s "../mod_exec.la" "mod_exec.la" )
/bin/bash ../libtool --mode=compile --tag=CC gcc -DHAVE_CONFIG_H  -DLINUX  -I.. -I../include -I../include -I/usr/include/libxml2 -I/usr/include/mysql -g2 -O2 -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration -DPR_SHARED_MODULE -c ../modules/mod_digest.c
libtool: compile:  gcc -DHAVE_CONFIG_H -DLINUX -I.. -I../include -I../include -I/usr/include/libxml2 -I/usr/include/mysql -g2 -O2 -Wall -fno-omit-frame-pointer -Werror=implicit-function-declaration -DPR_SHARED_MODULE -c ../modules/mod_digest.c  -fPIC -DPIC -o .libs/mod_digest.o
../modules/mod_digest.c: In function 'crc32_init':
../modules/mod_digest.c:321:13: error: implicit declaration of function 'EVP_MD_CTX_md_data' [-Werror=implicit-function-declaration]
   md_data = EVP_MD_CTX_md_data(ctx);
             ^~~~~~~~~~~~~~~~~~
../modules/mod_digest.c:321:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   md_data = EVP_MD_CTX_md_data(ctx);
           ^
../modules/mod_digest.c: In function 'crc32_update':
../modules/mod_digest.c:334:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   md_data = EVP_MD_CTX_md_data(ctx);
           ^
../modules/mod_digest.c: In function 'crc32_final':
../modules/mod_digest.c:347:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   md_data = EVP_MD_CTX_md_data(ctx);
           ^
../modules/mod_digest.c: In function 'crc32_free':
../modules/mod_digest.c:360:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   md_data = EVP_MD_CTX_md_data(ctx);
           ^
../modules/mod_digest.c: In function 'EVP_crc32':
../modules/mod_digest.c:394:8: error: implicit declaration of function 'EVP_MD_meth_new' [-Werror=implicit-function-declaration]
   md = EVP_MD_meth_new(NID_undef, NID_undef);
        ^~~~~~~~~~~~~~~
../modules/mod_digest.c:394:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   md = EVP_MD_meth_new(NID_undef, NID_undef);
      ^
../modules/mod_digest.c:395:3: error: implicit declaration of function 'EVP_MD_meth_set_input_blocksize' [-Werror=implicit-function-declaration]
   EVP_MD_meth_set_input_blocksize(md, CRC32_BLOCK);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../modules/mod_digest.c:396:3: error: implicit declaration of function 'EVP_MD_meth_set_result_size' [-Werror=implicit-function-declaration]
   EVP_MD_meth_set_result_size(md, CRC32_DIGEST_LENGTH);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../modules/mod_digest.c:397:3: error: implicit declaration of function 'EVP_MD_meth_set_app_datasize' [-Werror=implicit-function-declaration]
   EVP_MD_meth_set_app_datasize(md, sizeof(EVP_MD *) + sizeof(CRC32_CTX));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../modules/mod_digest.c:398:3: error: implicit declaration of function 'EVP_MD_meth_set_init' [-Werror=implicit-function-declaration]
   EVP_MD_meth_set_init(md, crc32_init);
   ^~~~~~~~~~~~~~~~~~~~
../modules/mod_digest.c:399:3: error: implicit declaration of function 'EVP_MD_meth_set_update' [-Werror=implicit-function-declaration]
   EVP_MD_meth_set_update(md, crc32_update);
   ^~~~~~~~~~~~~~~~~~~~~~
../modules/mod_digest.c:400:3: error: implicit declaration of function 'EVP_MD_meth_set_final' [-Werror=implicit-function-declaration]
   EVP_MD_meth_set_final(md, crc32_final);
   ^~~~~~~~~~~~~~~~~~~~~
../modules/mod_digest.c:401:3: error: implicit declaration of function 'EVP_MD_meth_set_cleanup' [-Werror=implicit-function-declaration]
   EVP_MD_meth_set_cleanup(md, crc32_free);
   ^~~~~~~~~~~~~~~~~~~~~~~
../modules/mod_digest.c:402:3: error: implicit declaration of function 'EVP_MD_meth_set_flags' [-Werror=implicit-function-declaration]
   EVP_MD_meth_set_flags(md, 0);
   ^~~~~~~~~~~~~~~~~~~~~
../modules/mod_digest.c: In function 'compute_digest':
../modules/mod_digest.c:1098:10: error: implicit declaration of function 'EVP_MD_CTX_new' [-Werror=implicit-function-declaration]
   pctx = EVP_MD_CTX_new();
          ^~~~~~~~~~~~~~
../modules/mod_digest.c:1098:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   pctx = EVP_MD_CTX_new();
        ^
../modules/mod_digest.c:1108:5: error: implicit declaration of function 'EVP_MD_CTX_free' [-Werror=implicit-function-declaration]
     EVP_MD_CTX_free(pctx);
     ^~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [Makefile:34: mod_digest.la] Error 1
make[1]: Leaving directory '/usr/local/proftpd/modules'
make: *** [Makefile:40: modules] Error 2
```

**Comment by Castaglia** [comment]
Looks like it's related to use OpenSSL (or LibreSSL?) library version involved.  Does Alpine use libressl?

**Comment by tspicer** [comment]
Yes, it defaults to libressl

**Comment by tspicer** [comment]
For Alpine 3.7 it is

```
        libressl \
        libressl-dbg \
        libressl-doc \
        libressl2.6-libssl \
        libressl2.6-libcrypto\
        libressl2.6-libtls\
```

I think Alpine 3.8 uses 2.7

**Comment by Castaglia** [comment]
Using this Dockerfile:
```
FROM alpine:3.7

RUN apk --no-cache add \
  --update \
  build-base \
  gettext-dev \
  gettext \
  git \
  libressl \
  libressl-dbg \
  libressl-dev \
  libressl-doc \
  libressl2.6-libssl \
  libressl2.6-libcrypto \
  libressl2.6-libtls \
  tzdata \
  zlib-dev

RUN git clone --depth 10 https://github.com/proftpd/proftpd.git
```
I'm able to reproduce the issue.  Fortunately, it's a quick fix; PR forthcoming.

**Comment by Castaglia** [comment]
[This PR](https://github.com/proftpd/proftpd/pull/738) should fix things.  Can you confirm?

**Comment by tspicer** [comment]
@Castaglia I can confirm that it will now build in both Alpine 3.7 and 3.8 with libressl2.6 and 2.7. 
Thank you!

**Comment by Castaglia** [comment]
Merged, and backported to the 1.3.6 branch.  Thanks!
